- hosts: all
  tasks:
          - name: creating a docker repository
            yum_repository:
                 description: "repo for docker"
                 name: "docker-ce"
                 baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                 gpgcheck: "no"

          - name: installing docker
            package:
                  name: "docker-ce-18.09.1-3.el7.x86_64"
                  state: present

          - name: starting docker service
            service:
                   name: docker
                   state: started
    
